name: Run tests
on: workflow_dispatch
jobs:
  test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - run: xcode-select -s /Applications/Xcode-15.2.app
      - run: xcodebuild -project Recipes.xcodeproj -scheme Recipes -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15,OS=17.2" test
